GET https://graph.instagram.com/me/media?fields=media_url&access_token=IGQVJVV3ptU2kyY0N4VkNnS3hfMXV5WUM4MV9oY3czNXZAKUi00ZAWpsOGpRWF9id3JqY1p3d3FVRDdFWUl3c2g0SW9Rd3hyWjFUaE5OMkdvb204X0Jvb1FMVXhxYjkzTmtJczhzelNza3ZAtU1IzbU9VYU9udWt5SGpyYmxv


